language: r
sudo: required
dist: trusty
addons:
  apt:
    update: true
cache:
  - packages
install:
  - tlmgr install luatex
  - tlmgr install l3build
  - tlmgr install cm etex knuth-lib latex-bin tex tex-ini-files unicode-data xetex
  - tlmgr install --no-depends babel ptex uptex ptex-base uptex-base ptex-fonts uptex-fonts platex uplatex
  - tlmgr install metafont mfware
  - tlmgr install graphics graphics-cfg graphics-def oberdiek
  - tlmgr install --no-depends fontspec
  - tlmgr install ifluatex lm lualibs luaotfload
  - tlmgr install --no-depends chemformula ctex mhchem siunitx unicode-math
  - tlmgr install --no-depends cjk
  - tlmgr install adobemapping amsfonts amsmath chemgreek cjkpunct ctablestack ec environ etoolbox fandol filehook ifxetex lm-math lualatex-math luatexbase luatexja ms pgf tools trimspaces ucharcat ulem units xcolor xecjk xkeyval xunicode zhmetrics zhnumber
  - tlmgr update --self --all --no-auto-install
  - chmod u+x ./travis/build.sh
  - chmod u+x ./travis/publish.sh
script: "./travis/build.sh"
after_success:
  - "./travis/publish.sh"
env:
  global:
  - GH_USER_NAME: mgomersbach
  - GH_PROJECT_NAME: pandoc-travis-setup
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/cv.pdf
  - TZ="Europe/Amsterdam"
  - secure: 'A3NzCLF8bXXPcHkTURD3cmLl/KO4YNobaNtQxXO1D4fflvQ0KNVSX9S/oX4F73En7i19+tMk/3emOWmT+gATzyWTbQ0WJnArsWp00X2nQ+lp9viOtVx8F8b9l3x/BYo2wpAWRNxe7nooH8w8pjg27Uk3AJK/jQKCEe7aXv18pRxZYjRheG83VjCOTXSiN37s+BbedVJytLDZ2Jy9g1jR7/1JdHs9k1APdL2NV6e+KY1+ziuf3XcP3BK564IWx7eqBEgG9v9r4KWUIRrUrgLA9snqTlT4Xe53fWOVTinl35Z+Njt+EB+D/lceRdP1Az1sHJQoxQ84gg2BZoahoK/rtgJdQ7MkTGdTonTUXU4grnQTNrFvdAvtjtteGaZ1wtSBrPwMw1/KsHJJ+2uVe92xjmxod7Hc26ED8tcKB3dlEeHb3zgqomQQIGcO58C15lA4bADDBEVF9kXi0GKYZcpk3UeOEyuCc/FxEcQt4KrDqKE95Fi3wSj4lM98+rrnaQmvpSEqAWK3VRuhlqXxOSeuUCM5PWTlkbVJL2JaxyYxHzXqJrV/K3QPjEHDoymoB7mNDtwC1okw/07Y/CD0GS2QR7Jf3240l+UEK1cC3gvE/hVjXvW1eVnWPbTATgBJe/44lEHRj++2mOscRiOaHuUGauvba1F/DYcxLEMgdhzNG3A='
