language: r
pandoc_version: 2.4
sudo: required
addons:
  apt:
    update: true
    packages:
    - librsvg2-bin
apt_packages:
  - librsvg2-bin
  - python-pygments
cache:
- pip
- packages
- directories:
  - /home/travis/texlive
before_install:
- pip install --user --upgrade pandocfilters
- tlmgr install luatex
- tlmgr install l3build
- tlmgr install cm etex knuth-lib latex-bin tex tex-ini-files unicode-data xetex
- tlmgr install --no-depends babel ptex uptex ptex-base uptex-base ptex-fonts uptex-fonts platex uplatex
- tlmgr install metafont mfware
- tlmgr install graphics graphics-cfg graphics-def oberdiek
- tlmgr install --no-depends fontspec
- tlmgr install ifluatex lm lualibs luaotfload
- tlmgr install --no-depends chemformula ctex mhchem siunitx unicode-math
- tlmgr install --no-depends cjk
- tlmgr install adobemapping amsfonts amsmath chemgreek cjkpunct ctablestack ec environ etoolbox fandol filehook ifxetex lm-math lualatex-math luatexbase luatexja ms pgf tools trimspaces ucharcat ulem units xcolor xecjk xkeyval xunicode zhmetrics zhnumber collection-fontsrecommended collection-langeuropean
- tlmgr update --self --all --no-auto-install
install:
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh
script: "./travis/build.sh"
after_success:
- "./travis/publish.sh"
env:
  global:
  - GH_USER_NAME: mgomersbach
  - GH_PROJECT_NAME: cv
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/cv.pdf
  - RESULT_MD_PATH=$TRAVIS_BUILD_DIR/cv-mdout.md
  - RESULT_DOCX_PATH=$TRAVIS_BUILD_DIR/cv.docx
  - RESULT_HTML_PATH=$TRAVIS_BUILD_DIR/cv.html
  - TZ="Europe/Amsterdam"
  - secure: 'mqP9djw67zNIJqZiP9VNfzHSOkWEAhoI8S68FxryplcNjLOYuQqyWpiqPaLzPgNhGxrqxoUY/AXsNm8g8/G+4K3L8ug6x6P7p7a//btcClX2OAH8SZutyholi7UyLUdZ0ewRP1GmtAO/7He961X1Krz6HbQRcye/hlgsDdl21lTCRzm5c1CX/y//PluH2a6XjJmah0xtubFqWJJQnoZ8FeTxR6CmtjJ/6OI5YJOdCyxdkdatOz+WmpiMTmYobvfGYK7zR9wN7zIqsDDDo4F/6BrhRHWNbjoYqenC/ZtGo20OfNi668SACi/rq1ReXGnZMip275bO0C7Iqi/hc2tGB5O9tEgX5w2O65bgByzNH5PmfpB3CTsVYS2isOCI52DYyKuLhP2Eh/bpnda2l6BJ/Z63mp3bAgHh34VfDxYqlr8QiSudfMNabNHxVaRPxECJFFWvwdklf+zRcdblTHr6KjryOvEnBx5wEKlstLhSQFoDIv3c94wWDblQd2ovaHNOqY3D7ElWU2R5fjdTy8qu2fED0VbuYyoxcYf9GPVcAvuC634eCx/X1ma6Ijx+2V+UignnocOd1eXu27RG98sYJWtIPPExGGNCJzn6pfSd9MlIjW5NeHDSfD0CePDeFRS3GGKHPSrVyqM4xDqxORx0Q1MMkeMZ3uz4pwQHLB1hWcc='
