name: Build and Deploy CV

on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
          make \
          texlive \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-xetex \
          pandoc \
          pandoc-plantuml-filter

    - name: Build CV Files
      run: make all

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cv-results
        path: |
          dist/cv-np.pdf
          dist/cv-mdout.md
          dist/cv-np.docx
          dist/cv.html

    - name: Setup Ruby
      uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408 
      with:
        ruby-version: '3.1'
        bundler-cache: true
        cache-version: 0
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Init Jekyll
      run: bundle init && bundle add jekyll
    - name: Build with Jekyll
      run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4